# Generated by Django 4.1.7 on 2023-02-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('platorm', models.CharField(max_length=50)),
                ('app_date', models.DateField()),
                ('last_contact', models.DateField()),
                ('job_description', models.CharField(max_length=10000000)),
                ('commentary', models.CharField(max_length=10000)),
                ('contact', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
