# Generated by Django 4.1.7 on 2023-02-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_description',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_contact',
            field=models.DateField(default=None),
        ),
    ]
