# Generated by Django 4.1.7 on 2023-02-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_application_last_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='platorm',
            new_name='platform',
        ),
    ]
